version: "3.9"

services:
  api:
    container_name: api
    image: node:16.15.1
    build: .
    ports:
      - 3000:3000
    depends_on:
      - db
  db:
    container_name: db
    image: postgres:latest
    ports:
      - 5431:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=default
